### ISSUE TITLE
Cant order pizza?

### ISSUE THREAD

**Issue by RossmacD** [eoanodea/swift-ui-pizza-app#1]
# ME AND MY SON HAVE BEEN TRYING FOR HOURS TO ORDER A PEPPERONI PIZZA ON THIS APP AND IT STILL HASNT ARRIVED???????

**Comment by eoanodea** [comment]
Have you tried to turn it off / back on?

**Comment by RossmacD** [comment]
All it shows me is this????
![Image of Yaktocat](https://kfckuekpwg-flywheel.netdna-ssl.com/wp-content/uploads/2019/11/corks96fm.jpg)

**Comment by eoanodea** [comment]
That's what we like to see
